services:
  redis-sync:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: cryptosniper2.0-sync
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis
    networks:
      - cryptosniper-network
    restart: always

  redis:
    image: redis:alpine
    container_name: cryptosniper2.0-redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data
    networks:
      - cryptosniper-network
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always

networks:
  cryptosniper-network:
    driver: bridge

volumes:
  redis-data: